maxwellfdfd_root = fileparts(mfilename('fullpath'));
addpath(maxwellfdfd_root);
addpath([maxwellfdfd_root, filesep, 'base']);
addpath([maxwellfdfd_root, filesep, 'diff']);
addpath([maxwellfdfd_root, filesep, 'dielconst']);
addpath([maxwellfdfd_root, filesep, 'example', filesep, '2d']);
addpath([maxwellfdfd_root, filesep, 'example', filesep, '3d']);
addpath([maxwellfdfd_root, filesep, 'grid']);
addpath([maxwellfdfd_root, filesep, 'integ']);
addpath([maxwellfdfd_root, filesep, 'io']);
addpath([maxwellfdfd_root, filesep, 'material']);
addpath([maxwellfdfd_root, filesep, 'modesolver']);
addpath([maxwellfdfd_root, filesep, 'petsc']);
addpath([maxwellfdfd_root, filesep, 'shape']);
addpath([maxwellfdfd_root, filesep, 'source']);
addpath([maxwellfdfd_root, filesep, 'vis']);